### ISSUE TITLE
Loading Checkpoints for Finetuning

### ISSUE THREAD

**Issue by ravioliasb** [gaasher/I-JEPA#14]
I am still fairly new to Pytorch. Is it possible to load the pth.tar checkpoint file from the original IJEPA database into your finetuning code? I believe your pretraining code saves the file as .ckpt.

**Comment by gaasher** [comment]
No since my code has slightly different implementations (I use lucidrains transformer, pytorch lightning, etc...)

**Comment by ravioliasb** [comment]
Hello,

Would you happen to have a checkpoint from your training that you could
share with me?
