### ISSUE TITLE
Double adding of positional embedding

### ISSUE THREAD

**Issue by jhairgallardo** [gaasher/I-JEPA#4]
Hello! Thank you for the work you put into this code. It is simple and easy to understand. I have a question regarding the forward function in the IJEPA_base class.  I see that the positional embeddings are being added 2 times. Is this a mistake or am I missing something?

https://github.com/gaasher/I-JEPA/blob/main/model.py#L141
```
def forward(self, x, target_aspect_ratio=1, target_scale=1, context_aspect_ratio=1, context_scale=1):
  #get the patch embeddings
  x = self.patch_embed(x)
  b, n, e = x.shape
  x = x + self.pos_embedding[:, :n] # HERE
  #add the positional embeddings
  x = x + self.pos_embedding # and again HERE
  #normalize the embeddings
  x = self.post_emb_norm(x)
  ...
```

Thank you.

**Comment by gaasher** [comment]
Thank you for the kind words! I'm glad this repo is proving useful to people. 

You are right, the positional embedding should not be added twice. Fixed this in my last commit.
